version: 2

updates:

  - directory: "/frontend/"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/backend/"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/redirects/"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
