# Overwrites the default docker-compose.yml with some development settings.
---

x-common: 
  NODE_ENV: &NODE_ENV "development"

services:
  
  
  frontend:
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV: *NODE_ENV
    networks:
      - default
    ports:
      - 6980:80
    volumes:
      - ./frontend/dist:/app/dist
      - ./frontend:/app:ro
    working_dir: /app
    command: /bin/nodemon --config /app/nodemon.json --watch /app


  backend:
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV: *NODE_ENV
    networks:
      - default
    ports:
      - 6981:80
    volumes:
      - ./backend/dist:/app/dist
      - ./backend:/app:ro
    working_dir: /app
    command: /bin/nodemon --config /app/nodemon.json --watch /app


  assets:
    networks:
      - default
    ports:
      - 6982:80


  redirects:
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV: *NODE_ENV
    networks:
      - default
    ports:
      - 6983:80
    volumes:
      - ./redirects/dist:/app/dist
      - ./redirects:/app:ro
    working_dir: /app
    command: /bin/nodemon --config /app/nodemon.json --watch /app


  tunnel:
    deploy:
      replicas: 0


networks:
  proxymesh:
    external: false