# Overwrites the default docker-compose.yml with some development settings.
---

x-common: 
  NODE_ENV: &NODE_ENV "development"
  settings:
    deployment:
      DEPLOY_CSS_BUILDER:                &deploy_css_builder         ${DEPLOY_CSS_BUILDER:-1}
    external_urls:
      TVDH_FRONTEND_URL_EXTERNAL:        &external_frontend_url      ${TVDH_FRONTEND_URL_EXTERNAL:-http://localhost:6980/}
      TVDH_BACKEND_SERVER_URL_EXTERNAL:  &external_backend_url       ${TVDH_BACKEND_SERVER_URL_EXTERNAL:-http://localhost:6981/}
      TVDH_ASSET_SERVER_URL_EXTERNAL:    &external_asset_server_url  ${TVDH_ASSET_SERVER_URL_EXTERNAL:-http://localhost:6982/}
      TVDH_REDIRECT_SERVER_URL_EXTERNAL: &external_redirects_url     ${TVDH_REDIRECT_SERVER_URL_EXTERNAL:-http://localhost:6983/}
    internal_urls:
      TVDH_FRONTEND_URL_INTERNAL:        &internal_frontend_url      ${TVDH_FRONTEND_URL_internal:-http://tvdh-dev-frontend:80}
      TVDH_BACKEND_SERVER_URL_INTERNAL:  &internal_backend_url       ${TVDH_BACKEND_SERVER_URL_internal:-http://tvdh-dev-backend:80}
      TVDH_ASSET_SERVER_URL_INTERNAL:    &internal_asset_server_url  ${TVDH_ASSET_SERVER_URL_internal:-http://tvdh-dev-assets:80}
      TVDH_REDIRECT_SERVER_URL_INTERNAL: &internal_redirects_url     ${TVDH_REDIRECT_SERVER_URL_internal:-http://tvdh-dev-redirects:80}


services:
  
  
  frontend:
    container_name: tvdh-dev-frontend
    hostname: tvdh-dev-frontend
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV: *NODE_ENV
      TVDH_FRONTEND_URL_EXTERNAL:        *external_frontend_url
      TVDH_BACKEND_SERVER_URL_EXTERNAL:  *external_backend_url
      TVDH_ASSET_SERVER_URL_EXTERNAL:    *external_asset_server_url
      TVDH_REDIRECT_SERVER_URL_EXTERNAL: *external_redirects_url
    networks:
      - default
    ports:
      - 6980:80
    volumes:
      - ./frontend/dist:/app/dist
      - ./frontend:/app:ro
    working_dir: /app
    command: /bin/nodemon --config /app/nodemon.json --watch /app


  backend:
    container_name: tvdh-dev-backend
    hostname: tvdh-dev-backend
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV: *NODE_ENV
      TVDH_FRONTEND_URL_EXTERNAL:        *external_frontend_url
      TVDH_BACKEND_SERVER_URL_EXTERNAL:  *external_backend_url
      TVDH_ASSET_SERVER_URL_EXTERNAL:    *external_asset_server_url
      TVDH_REDIRECT_SERVER_URL_EXTERNAL: *external_redirects_url
    networks:
      - default
    ports:
      - 6981:80
    volumes:
      - ./backend/dist:/app/dist
      - ./backend:/app:ro
    working_dir: /app
    command: /bin/nodemon --config /app/nodemon.json --watch /app


  assets:
    networks:
      - default
    ports:
      - 6982:80


  redirects:
    container_name: tvdh-dev-redirects
    hostname: tvdh-dev-redirects
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV: *NODE_ENV
      TVDH_FRONTEND_URL_EXTERNAL:        *external_frontend_url
      TVDH_BACKEND_SERVER_URL_EXTERNAL:  *external_backend_url
      TVDH_ASSET_SERVER_URL_EXTERNAL:    *external_asset_server_url
      TVDH_REDIRECT_SERVER_URL_EXTERNAL: *external_redirects_url
      SIGNAL_URL:   ${SIGNAL_URL}
      TELEGRAM_URL: ${TELEGRAM_URL}
      WHATSAPP_URL: ${WHATSAPP_URL}
    networks:
      - default
    ports:
      - 6983:80
    volumes:
      - ./redirects/dist:/app/dist
      - ./redirects:/app:ro
    working_dir: /app
    command: /bin/nodemon --config /app/nodemon.json --watch /app


  tunnel:
    deploy:
      replicas: 0


networks:
  proxymesh:
    external: false