# This docker compose file contains all you need to get the stack up and running.
---

x-common:
  NODE_ENV:                  &NODE_ENV             production
  TVDH_FRONTEND_URL:         &frontend_server_url  ${TVDH_FRONTEND_URL}
  TVDH_BACKEND_SERVER_URL:   &backend_server_url   ${TVDH_BACKEND_SERVER_URL}
  TVDH_ASSET_SERVER_URL:     &asset_server_url     ${TVDH_ASSET_SERVER_URL}
  TVDH_REDIRECT_SERVER_URL:  &redirect_server_url  ${TVDH_REDIRECT_SERVER_URL}

services:


  frontend:
    container_name: tvdh-frontend
    hostname: tvdh-frontend
    build: 
      context: ./.
      args:
        module: frontend
      dockerfile: dockerfile
      target: *NODE_ENV
    restart: unless-stopped
    environment:
      NODE_ENV:                 *NODE_ENV
      TVDH_FRONTEND_URL:        *frontend_server_url
      TVDH_BACKEND_SERVER_URL:  *backend_server_url 
      TVDH_ASSET_SERVER_URL:    *asset_server_url   
      TVDH_REDIRECT_SERVER_URL: *redirect_server_url
    networks:
      - proxymesh
      - default
    command: /bin/frontend

  backend:
    container_name: tvdh-backend
    hostname: tvdh-backend
    build: 
      context: ./.
      args:
        module: backend
      dockerfile: dockerfile
      target: *NODE_ENV
    restart: unless-stopped
    environment:
      NODE_ENV:                 *NODE_ENV
      TVDH_FRONTEND_URL:        *frontend_server_url
      TVDH_BACKEND_SERVER_URL:  *backend_server_url 
      TVDH_ASSET_SERVER_URL:    *asset_server_url   
      TVDH_REDIRECT_SERVER_URL: *redirect_server_url
    networks:
      - proxymesh
      - default
    command: /bin/backend

  assets:
    container_name: tvdh-assets
    hostname: tvdh-assets
    image: httpd:2-alpine
    restart: unless-stopped
    environment:
      NODE_ENV:                 *NODE_ENV
      TVDH_FRONTEND_URL:        *frontend_server_url
      TVDH_BACKEND_SERVER_URL:  *backend_server_url 
      TVDH_ASSET_SERVER_URL:    *asset_server_url   
      TVDH_REDIRECT_SERVER_URL: *redirect_server_url
    networks:
      - proxymesh
      - default
    volumes:
      - ./assets/public/:/usr/local/apache2/htdocs/:ro
      - ./assets/config/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro


  redirects:
    container_name: tvdh-redirects
    hostname: tvdh-redirects
    build: 
      context: ./.
      args:
        module: redirects
        bin_name: redirects
      dockerfile: dockerfile
      target: *NODE_ENV
    restart: unless-stopped
    environment:
      NODE_ENV:                 *NODE_ENV
      TVDH_FRONTEND_URL:        *frontend_server_url
      TVDH_BACKEND_SERVER_URL:  *backend_server_url 
      TVDH_ASSET_SERVER_URL:    *asset_server_url   
      TVDH_REDIRECT_SERVER_URL: *redirect_server_url
    networks:
      - proxymesh
      - default
    command: /bin/redirects

networks:
  proxymesh:
    external: true
  default:
    name: tvdh-internal