# Overwrites the default docker-compose.yml with some development settings.
---

x-common: 
  NODE_ENV:                  &NODE_ENV             "development"
  TVDH_FRONTEND_URL:         &frontend_server_url  ${TVDH_FRONTEND_URL:-http://localhost:6980/}
  TVDH_BACKEND_SERVER_URL:   &backend_server_url   ${TVDH_BACKEND_SERVER_URL:-http://localhost:6981/}
  TVDH_ASSET_SERVER_URL:     &asset_server_url     ${TVDH_ASSET_SERVER_URL:-http://localhost:6982/}
  TVDH_REDIRECT_SERVER_URL:  &redirect_server_url  ${TVDH_REDIRECT_SERVER_URL:-http://localhost:6983/}

services:
  
  
  frontend:
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV:                 *NODE_ENV
      TVDH_FRONTEND_URL:        *frontend_server_url
      TVDH_BACKEND_SERVER_URL:  *backend_server_url 
      TVDH_ASSET_SERVER_URL:    *asset_server_url   
      TVDH_REDIRECT_SERVER_URL: *redirect_server_url
    networks:
      - default
    ports:
      - 6980:80
    volumes:
      - ./frontend/dist:/app/dist
      - ./frontend:/app:ro
    working_dir: /app
    command: /bin/nodemon --config /app/nodemon.json --watch /app


  backend:
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV:                 *NODE_ENV
      TVDH_FRONTEND_URL:        *frontend_server_url
      TVDH_BACKEND_SERVER_URL:  *backend_server_url 
      TVDH_ASSET_SERVER_URL:    *asset_server_url   
      TVDH_REDIRECT_SERVER_URL: *redirect_server_url
    networks:
      - default
    ports:
      - 6981:80
    volumes:
      - ./backend/dist:/app/dist
      - ./backend:/app:ro
    working_dir: /app
    command: /bin/nodemon --config /app/nodemon.json --watch /app


  assets:
    networks:
      - default
    ports:
      - 6982:80


  redirects:
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV:                 *NODE_ENV
      TVDH_FRONTEND_URL:        *frontend_server_url
      TVDH_BACKEND_SERVER_URL:  *backend_server_url 
      TVDH_ASSET_SERVER_URL:    *asset_server_url   
      TVDH_REDIRECT_SERVER_URL: *redirect_server_url
    networks:
      - default
    ports:
      - 6983:80
    volumes:
      - ./redirects/dist:/app/dist
      - ./redirects:/app:ro
    working_dir: /app
    command: /bin/nodemon --config /app/nodemon.json --watch /app

networks:
  proxymesh:
    external: false