# Overwrites the default docker-compose.yml with some development settings.
---

x-common: 
  NODE_ENV:                  &NODE_ENV             "development"
  TVDH_FRONTEND_URL:         &frontend_server_url  "http://localhost:8080/"
  TVDH_BACKEND_SERVER_URL:   &backend_server_url   "http://localhost:8081/"
  TVDH_ASSET_SERVER_URL:     &asset_server_url     "http://localhost:8082/"
  TVDH_REDIRECT_SERVER_URL:  &redirect_server_url  "http://localhost:8083/"

services:
  
  
  # frontend:
  #     target: *NODE_ENV
  #   environment:
  #     NODE_ENV:                 *NODE_ENV
  #     TVDH_FRONTEND_URL:        *frontend_server_url
  #     TVDH_BACKEND_SERVER_URL:  *backend_server_url 
  #     TVDH_ASSET_SERVER_URL:    *asset_server_url   
  #     TVDH_REDIRECT_SERVER_URL: *redirect_server_url
  #   networks:
  #     - default
  #   ports:
  #     - 8080:80


  backend:
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV:                 *NODE_ENV
      TVDH_FRONTEND_URL:        *frontend_server_url
      TVDH_BACKEND_SERVER_URL:  *backend_server_url 
      TVDH_ASSET_SERVER_URL:    *asset_server_url   
      TVDH_REDIRECT_SERVER_URL: *redirect_server_url
    networks:
      - default
    ports:
      - 8081:80
    volumes:
      - ./backend/src/:/src/app/:ro


  assets:
    networks:
      - default
    ports:
      - 8082:80


  redirects:
    build: 
      target: *NODE_ENV
    environment:
      NODE_ENV:                 *NODE_ENV
      TVDH_FRONTEND_URL:        *frontend_server_url
      TVDH_BACKEND_SERVER_URL:  *backend_server_url 
      TVDH_ASSET_SERVER_URL:    *asset_server_url   
      TVDH_REDIRECT_SERVER_URL: *redirect_server_url
    networks:
      - default
    ports:
      - 8083:80
    volumes:
      - ./redirects/src/:/src/app/:ro


networks:
  proxymesh:
    external: false