name: Deploy GitHub Pages

# Deploy on push to main, every week, or manually
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # Build and deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Get GitHub Pages URL
        id: get_pages_url
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pages)
          echo "url=$(echo $response | jq -r .html_url)" >> $GITHUB_OUTPUT
      - name: Install Typst using Snap
        run: sudo snap install typst
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"
      - name: Install NPM dependencies
        run: npm clean-install
      - name: Build project
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_PAGES_URL: ${{ steps.get_pages_url.outputs.url }}
          PHONE: ${{ secrets.PHONE }}
          email: ${{ secrets.EMAIL }}
      - name: Copy output to deploy folder
        run: |
          mkdir --parents ./public/
          cp ./index.html ./public/
          cp ./tailwind.output.css ./public/
          cp ./curriculum-vitae.pdf ./public/
        # The 'favicon.ico' is optional 
        # [ -f favicon.ico ] && cp favicon.ico ./public/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public/'

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Production ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        id: deployment
        uses: actions/deploy-pages@v4
