name: Deploy GitHub Pages

# Deploy on push to main, every week, or manually
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Build using Nix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix build
  
  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy output to deploy folder
        run: |
          mkdir --parents public
          cp --recursive ./result --verbose --dereference --target-directory=public --force
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
