name: Nix Flake Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Run Nix Flake Check
        run: nix flake check